name = "worker"
type = "javascript"
workers_dev = true
compatibility_date = "2022-10-09"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration

[durable_objects]
bindings = [
  { name = "LATEST_PUSHED_DATES", class_name = "Latest_Pushed_Dates" } # the `class_name` uses the Rust struct identifier name
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Latest_Pushed_Dates"] # Array of new classes
